### ISSUE TITLE
Command line tool produces wrong response times

### ISSUE THREAD

**Issue by semmel** [hellgrenj/hulken#4] opened 2015-01-05 21:29 UTC
Hi,
when I use the command line tool to test a simple CORS AJAX web service I get response times wrong by a factor of 50.

I tested with different web services, here is an example.

```
$ hulken bitcoin_options.json 
setting options from file bitcoin_options.json
number of times to repeat each request set to 10
target url set to https://blockchain.info/ticker
request file path (including file name) set to ./bitcoin_request.json
the following characters (in an url) will cause a request to be skipped :,{,}
happyTimeLimit set to 10
numberOfHulkenAgents set to 1
slowRequestsTimeLimit set to 0.5
angryOnFailedRequest set to true
chatty set to true
happyMessage set to HULKEN PLEASED, YOU MAY CONTINUE WITH YOUR DAY!
angryMessage set to HULKEN ANGRY! HULKEN SMASH!
minWaitTime set to 500
maxWaitTime set to 4000
headers set to {"Accept":"application/json, text/javascript, */*; q=0.01","Accept-Encoding":"gzip, deflate, sdch","Accept-Language":"en,de;q=0.8,en-US;q=0.6,it;q=0.4","Cache-Control":"no-cache","Connection":"keep-alive","Pragma":"no-cache","User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.45 Safari/537.36"}

 ..::HULKEN SMASH::.. 

initiating agent 1 of 1
... no login required, continuing with anonymous user
... starting to execute requests
GET ?cors=true (by agent 1/1) responded in 8.494 seconds
GET ?cors=true (by agent 1/1) responded in 7.47 seconds
GET ?cors=true (by agent 1/1) responded in 7.398 seconds
GET ?cors=true (by agent 1/1) responded in 9.561 seconds
GET ?cors=true (by agent 1/1) responded in 9.27 seconds
GET ?cors=true (by agent 1/1) responded in 8.376 seconds
GET ?cors=true (by agent 1/1) responded in 7.283 seconds
GET ?cors=true (by agent 1/1) responded in 7.397 seconds
GET ?cors=true (by agent 1/1) responded in 9.067 seconds
GET ?cors=true (by agent 1/1) responded in 11.115 seconds
.. all requests have been executed

 **************** RESULT ******************
number of concurrent requests 10
number of hulken agents running 1
number of unique requests 1
number of slow requests 10
number of failed requests 0
total seconds elapsed  15.058
avg response time (in seconds)  8.5431
req/sec 0.66
random request wait time (in seconds) 0.5-4
******************************************
HULKEN ANGRY! HULKEN SMASH!
```

In contrast when I employ the Chrome browser API using jQuery I get an average response time of `123ms`. The browser cache is disabled and I confirmed that the `23` request in my test yielded unique api responses. The JavaScript measurement is consistent with the measured times in the Network panel of the Chrome developer tools. 
Here is the simple code:
```javascript
var
	dT = 200,
	varDT = 100;

function callingBC()
{
	$.ajax("https://blockchain.info/ticker",
		{
			data: { cors: true },
			dataType: "json"
		})
		.then((function(startTime)
		{
			return function( data, textStatus, jqXHR )
			{
				responseTimes.push(Date.now() - startTime);

				if (!abort)
				{
					var waitFor = dT + Math.random() * varDT - varDT / 2;

					setTimeout(callingBC, waitFor);
				}
			};
		}(Date.now()))
		, function( jqXHR, textStatus, errorThrown )
		{
			console.log(textStatus, errorThrown);
		}
	);
}
```
What am I doing wrong?

Best regards
Semmel

**Comment by hellgrenj** [comment] 2015-01-05 22:14
Hi Semmel! 

I was unable to reproduce this on my MacBook Pro. I tried several times and got an average response time of : 0.1232 (seconds).  I did however notice that the header "Connection":"keep-alive" stops the process from closing down after completion. 

1) What does your requests file look like?
2) Why are you passing in "tokensSkippingRequest": ":,{,}" ?
3) What machine / OS are you running the tests on?
4) Do you get the same response times consistently? 

Best regards,
Johan

**Comment by hellgrenj** [comment] 2015-01-06 11:17
I have now tried this particular test in several environments and I can not reproduce the response times you are seeing. This leads me to the conclusion that there is no bug in the measurement of response times (nor by a factor of 50 as you reported). I have off course also tried hulken against different systems and services and I can't see the issue you are describing in any of my tests. 

When I executed your scenario in the environments below I received average response times around 0.123 seconds:
win 8.1 node 0.10.29 powershell (VM Virtualbox on MacBook Pro)
mac os x Yosemite 10.10.1 Iterm2 bash node 0.10.28
(all tests executed from Sweden)


When I executed your scenario on my raspberry pi
(raspberry pi running raspbian node 0.10.25)
i got an average response time of 0.6 seconds. 
(all tests executed from Sweden)

Whenever you execute stress tests, no matter what tool you use, it is a good idea to keep an eye on the machine/environment executing the test. If the system under test isn't bothered by the load perhaps the machine or environment executing the test is the bottleneck. There are off course a lot of other things that matters; where is the system under test located and where is the machine executing the test, what's your bandwidth, etc … 

It is very difficult for me to say why you got those response times but the measurements are not off by 50, therefore i am closing this issue as “invalid”.  

Best regards,
Johan

**Closed by hellgrenj** 2015-01-06 11:17 UTC

**Comment by semmel** [comment] 2015-01-06 16:52
Hey Johan,
thanks for the swift response.

>I did however notice that the header "Connection":"keep-alive" stops the process from closing down after completion.

Right, I removed that line and now I get response times closer to those observed in the browser! However I cannot reproduce the response times last reported when I reinsert that header line: Instead after finishing the requests the command line process just takes approx. 30 seconds longer to quit.

>1) What does your requests file look like?

```
[{
  "method":"get",
  "path":"?cors=true"
 }
]
```
>2) Why are you passing in "tokensSkippingRequest": ":,{,}" ?

no reason took the generated file
>3) What machine / OS are you running the tests on?

node 'v0.10.28'
ProductName:	Mac OS X
ProductVersion:	10.9.5

>4) Do you get the same response times consistently?

Not consistently, no. Today I get about `200ms` response, though once with identical conditions I managed to reproduce a `hulken` run getting about `6000ms` like reported previously. Very strange....

I noticed something else: In the output it says *number of concurrent requests 8* though my initial JS example is sequential. Because `hulken` produces the request response times line by line I assumed that the requests were fired sequentially too. If that's not the case then I have to adapt my reference measurement.

**Comment by hellgrenj** [comment] 2015-01-06 17:41
The  "Connection":"keep-alive"  header does not impact the response times it only keeps the process alive since I don't explicitly close it when the test is finished. 

Hulken does not execute the requests sequentially no. Hulken executes the requests in parallel with respect to the randomised wait times. Hulken prints info about a request when the response is handled. 
(try to increase the number of agents executing requests and this will be more obvious)

I also recommend you checkout the ./tests/integrations.js file (and also execute it) for more insight in how the tool works.
